// src/js/engine/geometry.js

/**
 * The default cabinet parameters used to initialize the application and populate UI fields.
 * Includes external dimensions, compressor step geometry, and standard wall thicknesses.
 */
export const DEFAULT_CABINET = Object.freeze({
  H: 1680,  W: 800,  D: 630,
  Hb: 260, Db1: 210, Db2: 230,
  doorGap: 10, packingPos: 15, airGap: 5,
  walls: {
    freezer: {
      top:    59.4, bottom: 70, left:   59.4,
      right:  59.4, door:   59.4, rear:  60,
    },
    refrigerator: {
      top:     70, bottom1: 40, bottom2: 40, bottom3: 40,
      left:    40, right:   40, door:    40, rear:    60,
    },
  },
});

/**
 * Formats a generic geometry object into the specific format required by the 
 * earlier versions of the volumetric engine (`calcLeafGross`).
 * 
 * @param {object} geom - The unified geometry object.
 * @returns {object} The geometry mapped to the { external, wallThicknessesByType } schema.
 */
export function toVolumeFormat(geom) {
  const { H, W, D, walls } = geom;
  const t = {
    fresh: {
      top: walls.refrigerator.top,
      bottom: walls.refrigerator.bottom1,
      left: walls.refrigerator.left,
      right: walls.refrigerator.right,
      rear: walls.refrigerator.rear,
      door: walls.refrigerator.door
    },
    freezer: {
      top: walls.freezer.top,
      bottom: walls.freezer.bottom,
      left: walls.freezer.left,
      right: walls.freezer.right,
      rear: walls.freezer.rear,
      door: walls.freezer.door
    },
  };
  
  return {
    external: { height: H, width: W, depth: D },
    wallThicknessesByType: t,
    airGap: 0
  };
}

/**
 * Translates the unified geometry object generated by the UI into the specific, 
 * flat schema required by the thermodynamic solver (`heatLoad.js`).
 * 
 * This function resolves dynamic properties based on the arrangement of the compartments 
 * (e.g., determining if the partition divider acts as the freezer's bottom wall or the refrigerator's top wall).
 *
 * @param {object} geom - The unified geometry object containing dimensions, compartments, and walls.
 * @returns {object} A flat object containing explicitly mapped boundaries (e.g., tFtop, tRfloor) required for thermal conduction calculations.
 */
export function toThermalFormat(geom) {
  const { H, W, D, Hf, Hr, Hb, Db1, Db2, doorGap, packingPos, walls, dividerThickness } = geom;

  // Determine the configuration type by examining the first (topmost) compartment.
  const isBottomFreezer = geom._compartments && geom._compartments[0].type === 'fresh';
  const isTopFreezer    = geom._compartments && geom._compartments[0].type === 'freezer';
  
  // Fallback to 60mm for configurations lacking explicit layout data (e.g., DEFAULT_CABINET)
  const divThick = dividerThickness ?? 60; 

  return {
    H, W, D, Hf, Hr, Hb, Db1, Db2, doorGap, packingPos,

    // Freezer walls: Assign the partition thickness to tFtop in a bottom freezer configuration, 
    // or tFbottom in a top freezer configuration.
    tFtop:    isBottomFreezer ? divThick : walls.freezer.top,
    tFleft:   walls.freezer.left,
    tFright:  walls.freezer.right,
    tFbottom: isTopFreezer ? divThick : walls.freezer.bottom,
    tFdoor:   walls.freezer.door,
    tFback:   walls.freezer.rear,
    tEvaBack: walls.freezer.rear,

    // Refrigerator walls: Assign the partition thickness to tRfloor in a bottom freezer configuration, 
    // or tRtop in a top freezer configuration.
    tRtop:    isTopFreezer ? divThick : walls.refrigerator.top,
    tRleft:   walls.refrigerator.left,
    tRright:  walls.refrigerator.right,
    tRback:   walls.refrigerator.rear,
    tRdoor:   walls.refrigerator.door,

    tRbottom1: walls.refrigerator.bottom1,
    tRbottom2: walls.refrigerator.bottom2,
    tRbottom3: walls.refrigerator.bottom3,

    // Isolate the exterior stepped floor thickness for the freezer compartment 
    // (fallback to refrigerator mappings if undefined).
    tFfloor1: walls.freezer.bottom1 ?? walls.refrigerator.bottom1,
    tFfloor2: walls.freezer.bottom2 ?? walls.refrigerator.bottom2,
    tFfloor3: walls.freezer.bottom3 ?? walls.refrigerator.bottom3,

    // Explicitly assign the internal partition to tRfloor for bottom freezer configs.
    tRfloor: isBottomFreezer ? divThick : walls.refrigerator.bottom1,
  };
}

/**
 * Upgrades a legacy configuration file (Schema v1.0) to the current unified format (Schema v2.0).
 * Prevents application crashes when loading older saved project files.
 *
 * Old config schema: { schemaVersion:"1.0", meta:{...}, cabinet:{ external, wallThicknessesByType, airGap, layout } }
 *
 * @param {object} oldConfig - The parsed JSON data from a v1.0 save file.
 * @returns {object} A valid v2.0 configuration object ready for precise calculation and simulation.
 * @throws {Error} If the provided configuration object lacks a valid `cabinet` structure.
 */
export function upgradeConfig(oldConfig) {
  if (!oldConfig?.cabinet) throw new Error('Invalid old config');

  const { external, wallThicknessesByType, airGap, layout } = oldConfig.cabinet;
  const def = DEFAULT_CABINET;

  // Re-map the nested, type-based wall thicknesses into the unified schema.
  const walls = {
    freezer: {
      top:    wallThicknessesByType?.freezer?.top    ?? def.walls.freezer.top,
      bottom: wallThicknessesByType?.freezer?.bottom ?? def.walls.freezer.bottom,
      left:   wallThicknessesByType?.freezer?.left   ?? def.walls.freezer.left,
      right:  wallThicknessesByType?.freezer?.right  ?? def.walls.freezer.right,
      door:   wallThicknessesByType?.freezer?.door   ?? def.walls.freezer.door,
      rear:   def.walls.freezer.rear   // old format had no "rear" defined for the freezer
    },
    refrigerator: {
      top:    wallThicknessesByType?.fresh?.top    ?? def.walls.refrigerator.top,
      bottom1:wallThicknessesByType?.fresh?.bottom ?? def.walls.refrigerator.bottom1,
      bottom2:def.walls.refrigerator.bottom2,
      bottom3:def.walls.refrigerator.bottom3,
      left:   wallThicknessesByType?.fresh?.left   ?? def.walls.refrigerator.left,
      right:  wallThicknessesByType?.fresh?.right  ?? def.walls.refrigerator.right,
      door:   wallThicknessesByType?.fresh?.door   ?? def.walls.refrigerator.door,
      rear:   def.walls.refrigerator.rear
    }
  };

  const geom = {
    H: external.height,
    W: external.width,
    D: external.depth,
    Hf: def.Hf,
    Hr: def.Hr,
    Hb: def.Hb,
    Db1: def.Db1,
    Db2: def.Db2,
    doorGap: def.doorGap,
    packingPos: def.packingPos,
    airGap: airGap ?? def.airGap,
    walls
  };

  return {
    schemaVersion: '2.0',
    meta: {
      ...oldConfig.meta,
      updatedAt: new Date().toISOString(),
      upgradedFrom: oldConfig.schemaVersion
    },
    cabinet: {
      geometry: geom,
      layout
    },
    thermal: oldConfig.thermal // Ensure thermal settings are preserved without modification
  };
}