const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindow() {
  // Create the native desktop window.
  const win = new BrowserWindow({
    width: 1366,
    height: 900,
    autoHideMenuBar: true, // Hides the default Windows "File/Edit/View" menu bar
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true
    }
  });

  // Load the compiled index.html generated by Vite
  win.loadFile(path.join(__dirname, 'dist', 'index.html'));
}

// This method will be called when Electron has finished initialization
app.whenReady().then(createWindow);

// Quit when all windows are closed (standard Windows behavior)
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});